export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL';
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';

export const SELECTED_VIDEO_REQUEST = ' SELECTED_VIDEO_REQUEST';
export const SELECTED_VIDEO_SUCCESS= ' SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAIL = ' SELECTED_VIDEO_FAIL';

export const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';
export const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';
export const RELATED_VIDEO_FAIL = 'RELATED_VIDEO_FAIL';

export const SEARCHED_VIDEO_REQUEST = 'SEARCHED_VIDEO_REQUEST';
export const SEARCHED_VIDEO_SUCCESS = 'SEARCHED_VIDEO_SUCCESS';
export const SEARCHED_VIDEO_FAIL = 'SEARCHED_VIDEO_FAIL';